name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v4

      - name: 安装 Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 安装依赖
        run: npm install

      - name: 打包项目
        run: npm run build

      - name: 上传产物
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

      - name: 部署
        uses: actions/deploy-pages@v2
